language: java

jdk:
  - openjdk16
  - openjdk15
  - openjdk11
  - openjdk8

services:
  - docker

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - ./travis/after_success.sh

env:
  global:
    secure: b6V2NZgMyTmsTBo27a8YdEY3ZdPBY6G+ZwEIEJP9/xUABpG967MhXarIGvryIWco4WTnYVQeubstQQHP6zkGRccWpYDRmXRng9e8MvzATzHS67Z1YTVX+I5PQIxBSoKi6QgJMSnvCVU2REhsSfVqHYguYZ5ZBkIy9QidBmu2VElE36aFKOzFG96jLCMLaniM3ASu+Mcf58M5QRVNEQf5qTHAGubYY0k5Joib9oxlph4q+8zfvozD5XSlwDe9Hxd8Vls+jvCgWBPvj7ydf8qjQHfmaO+KdIa/yjS+a5Y5ILnLvNFPRIAkZSwTuLhaoNCGeLCjydCsL+eN9wpys568FlKz3cJvhDocVypXMXRXxFY/UnNZEoByxdEhB099cgbmHaGwGDXjC5xT9xgNsW5f+VkO1yW5WbiQWXH4vrbbvI/tuhWA3NBSc9bMTGXxRvIR4t30CDYGqIh1Rp9h2oz8lMtlg01GsXpRmPE7dX4Ec97vSoh5T4ddn7CIb6s98UgdeR3XA2uuGSgdyP3qUGh9jqdQJO0BLvql+QHqZQylW9KTjkxzr4py+90P4660weG0swGHxUeoZYQnJPU7h1VSydXIFdl9iGBcsTy8faeG5bBdBjZzYqBkgML6/yjDNvw/4VT1K+aWaJGK0QVa5GrQ1x4KIWRTTxpVep4zcS425RA=

addons:
  sonarcloud:
    organization: "mybatis"
    token:
      secure: "Hci6OzYOkzcy6CUWlJTe5zLHRFRUO0KVe5o/V3RvtWndz3/4CHmWkP/dZjMxYliUiOZ+UR9uQhVH6dqcKSR94vb++CiDDxorkzqWiWlMEZMaWflvOe/dQsvKwPGZ/QO32RR+Boh0b3VrWZIOsu84wpYAMyZmncXJ0Y2QvmodiqtChYvV+8F6ZimNCfkGZRJhRfKnAbqFsPlB/c9TQc6hW0Dg9rWtjsbQFVtnkIhu48NdVtylPidHUSQWj0JsVQRvWUmBkoMr7lFSImyCW2r7X5vrVIccH6LTPk1Q5V4A8UgCtHhSnQcAFmFi/cxpUqIRgfjvB3azjp/Z9PrzZUFLgRzo3piKZkuQpI5a9xAANH7xcfiZfqztapLx6glW1c5oHRvk771dLcm5+he6JxKIKBBt8BFGOpkXG5NyvDOGHA4bo36oz6VL2L7oVRrS0KdgfFBmQFCuB0cRH3sQGGE4TjyghJUWLnYDRvQGz1IiX94xPUf/+MOHrMeLs/QIROOKJRTMyNC9u+ZQJeQK+i20b4A7euFP8fwzvQRJm3EgEuQf501raPUUDv+Kh4YskDg86fDHxJrmrpM4UsFe6V/WDPFGZc1zRJJRI5yeiaVg5M0KAt5SYfrV1YcjU5ExvKj7x9vyQ3pcfpLlKIKyFKBJMRryMQLNCn+frEJbxlrxJDE="
